<?xml version="1.0"?>

<!-- Author: Ethan Hy, Email: eh2517@ic.ac.uk-->
<!-- Author: Tan Tai Ming, Email: tmt111@ic.ac.uk-->
<!-- Adapted from PX4 Iris Quadcopter files for Imperial College London, Group Design Project 2020, Autonomous Drone Delivery-->

<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Main multirotor link -->
  <xacro:macro name="multirotor_base_macro"
    params="robot_namespace mass body_length body_width body_height mesh_file mesh_scale color *inertia">
    <link name="base_link"></link>

    <joint name="base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_link_inertia" />
    </joint>

    <link name="base_link_inertia">
      <inertial>
        <mass value="${mass}" />  <!-- [kg] -->
        <origin xyz="0 0 0" />
        <xacro:insert_block name="inertia" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="model://final_drone/meshes/${mesh_file}"
            scale="${mesh_scale}" />
          <!-- <box size="${body_width} ${body_width} ${body_height}"/> --> <!-- [m] [m] [m] -->
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${body_length} ${body_width} ${body_height}" /> <!-- [m] [m] [m] -->
        </geometry>
      </collision>
    </link>

    <!-- attach multirotor_base_plugin to the base_link -->
    <gazebo>
      <plugin filename="libgazebo_multirotor_base_plugin.so" name="rosbag">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <linkName>base_link</linkName>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
    <gazebo reference="base_link">
      <material>Gazebo/${color}</material>
      <collision name='base_link_inertia_collision'>
        <surface>
          <contact>
            <ode>
              <min_depth>0.001</min_depth>
              <max_vel>0.0</max_vel>
            </ode>
          </contact>
          <friction>
            <ode/>
          </friction>
        </surface>
      </collision>
   </gazebo>
  </xacro:macro>

  <!-- arm joint and link -->
  <xacro:macro name="arm"
    params="robot_namespace side parent arm_number mass_arm color mesh mesh_scale *origin *inertia">
    <joint name="arm_${arm_number}" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <parent link="${parent}" />
      <child link="arm_${arm_number}" />
      <dynamics damping="0.3"/>
    </joint>

    <link name="arm_${arm_number}">
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
      <inertial>
        <mass value="${mass_arm}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
          <!--mesh filename="package://final_drone/meshes/rotor_arm_part.STL"
           scale="${mesh_scale}" /-->
          <mesh filename="model://final_drone/meshes/rotor_arm_part_${side}.stl"
            scale="${mesh_scale}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${arm_width} ${arm_length} ${arm_height}" /> <!-- [m] [m] [m] -->
        </geometry>
      </collision>
    </link>
    <gazebo reference="arm_${arm_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <!-- stand joint and link -->
  <xacro:macro name="stand"
    params="robot_namespace arm_number stand_direction mass_stand color mesh mesh_scale *origin *inertia">
    <joint name="stand_${stand_direction}" type="fixed">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <parent link="arm_${arm_number}" />
      <child link="stand_${stand_direction}" />
    </joint>

    <link name="stand_${stand_direction}">
      <inertial>
        <mass value="${mass_stand}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
          <!--mesh filename="package://final_drone/meshes/rotor_arm_part.STL"
           scale="${mesh_scale}" /-->
          <mesh filename="model://final_drone/meshes/stand_${stand_direction}.stl"
            scale="${mesh_scale}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${stand_width} ${stand_length} ${stand_height}" /> <!-- [m] [m] [m] -->
        </geometry>
      </collision>
    </link>
    <gazebo reference="stand_${stand_direction}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>





  <!-- Rotor joint and link -->
  <xacro:macro name="vertical_rotor"
    params="robot_namespace parent suffix direction motor_constant moment_constant arm_number mass_rotor radius_rotor time_constant_up time_constant_down max_rot_velocity motor_number rotor_drag_coefficient rolling_moment_coefficient color mesh mesh_scale *origin *inertia">
    <joint name="rotor_${motor_number}_joint" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <!-- TODO(ff): not currently set because it's not yet supported -->
      <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
      <parent link="arm_${arm_number}" />
      <child link="rotor_${motor_number}" />

    </joint>
    <!-- TODO(ff): not currently set because it's not yet supported -->
    <!-- <gazebo reference="rotor_${motor_number}_joint"> <axis> <xyz>0 0 1</xyz>
      <limit> <velocity> ${max_rot_velocity} </velocity> </limit> </axis> </gazebo> -->
    <link name="rotor_${motor_number}">
      <inertial>
        <mass value="${mass_rotor}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
          <!-- <cylinder length="0.005" radius="${radius_rotor}"/> --> <!-- [m] -->
          <!-- <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae" -->
          <mesh filename="model://final_drone/meshes/${mesh}.stl"
            scale="${mesh_scale}" />
          <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.005" radius="${radius_rotor}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>
    <gazebo>
      <plugin name="${suffix}_motor_model" filename="libgazebo_motor_model_gdp2020.so"> <!-- Amended to use the GDP2020_ADD motor plugin. -Tai Ming- -->
        <robotNamespace>${robot_namespace}</robotNamespace>
        <jointName>rotor_${motor_number}_joint</jointName>
        <linkName>rotor_${motor_number}</linkName>
        <turningDirection>${direction}</turningDirection>
        <timeConstantUp>${time_constant_up}</timeConstantUp>
        <timeConstantDown>${time_constant_down}</timeConstantDown>
        <maxRotVelocity>${max_rot_velocity}</maxRotVelocity>
        <motorConstant>${motor_constant}</motorConstant>
        <momentConstant>${moment_constant}</momentConstant>
        <commandSubTopic>/gazebo/command/motor_speed</commandSubTopic>
        <motorNumber>${motor_number}</motorNumber>
        <rotorDragCoefficient>${rotor_drag_coefficient}</rotorDragCoefficient>
        <rollingMomentCoefficient>${rolling_moment_coefficient}</rollingMomentCoefficient>
        <motorSpeedPubTopic>/motor_speed/${motor_number}</motorSpeedPubTopic>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
        <!--
        <gazebo_joint_control_pid>
          <p>0.1</p>
          <i>0</i>
          <d>0</d>
          <iMax>0</iMax>
          <iMin>0</iMin>
          <cmdMax>3</cmdMax>
          <cmdMin>-3</cmdMin>
        </gazebo_joint_control_pid>
      -->
      </plugin>
    </gazebo>
    <gazebo reference="rotor_${motor_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="ultrasonic_sensor" params="robot_namespace sensor_id parent *origin ros_topic update_rate min_range max_range field_of_view ray_count arm_number suffix">
    <joint name="${sensor_id}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${sensor_id}_link"/>
    </joint>

    <link name="${sensor_id}_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.000000017" ixy="0" ixz="0" iyy="0.000000017" iyz="0" izz="0.000000017" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
          <!-- mesh filename="package://hector_sensors_description/meshes/sonar_sensor/max_sonar_ez4.dae"/ -->
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${sensor_id}_link">
      <sensor type="ray" name="${sensor_id}">
        <always_on>true</always_on>
        <update_rate>${update_rate}</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>${ray_count}</samples>
              <resolution>1</resolution>
              <min_angle>-${field_of_view/2}</min_angle>
              <max_angle> ${field_of_view/2}</max_angle>
            </horizontal>
            <vertical>
              <samples>${ray_count}</samples>
              <resolution>1</resolution>
              <min_angle>-${field_of_view/2}</min_angle>
              <max_angle> ${field_of_view/2}</max_angle>
            </vertical>
          </scan>
          <range>
            <min>${min_range}</min>
            <max>${max_range}</max>
            <resolution>0.01</resolution>
          </range>
        </ray>

        <plugin name="gazebo_ros_sonar_controller" filename="libhector_gazebo_ros_sonar.so">
          <gaussianNoise>0.005</gaussianNoise>
          <topicName>${ros_topic}</topicName>
          <frameId>${sensor_id}_link</frameId>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  
</robot>
