drone:  
 # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  
  
  # Position Controllers ---------------------------------------
  arm_0_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_0
    pid: {p: 5.0, i: 3.0, d: 3.0}
  arm_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1
    pid: {p: 5.0, i: 3.0, d: 3.0}
